// <auto-generated />
using System;
using CyanCMS.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyanCMS.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CyanCMS.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Company_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Company_Id"));

                    b.Property<string>("Audit_FecAct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audit_FecCre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audit_UsuAct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audit_UsuCre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company_Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Company_Estado")
                        .HasColumnType("int");

                    b.Property<string>("Company_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company_Pk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Company_Telefono")
                        .HasColumnType("int");

                    b.Property<string>("File_Base64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File_Tamanio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan_Pk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id_Fk")
                        .HasColumnType("int");

                    b.HasKey("Company_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("CyanCMS.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Rol_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rol_Id"));

                    b.Property<string>("Audit_FecAct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audit_FecCre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audit_UsuAct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audit_UsuCre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol_Estado")
                        .HasColumnType("int");

                    b.Property<string>("Rol_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol_Pk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rol_Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("CyanCMS.Domain.Entities.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<string>("Audit_FecAct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audit_FecCre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audit_UsuAct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audit_UsuCre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan_Pk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rol_Id")
                        .HasColumnType("int");

                    b.Property<int>("Rol_Id_Fk")
                        .HasColumnType("int");

                    b.Property<string>("User_Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Estado")
                        .HasColumnType("int");

                    b.Property<string>("User_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Pk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Telefono")
                        .HasColumnType("int");

                    b.Property<string>("User_Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Id");

                    b.HasIndex("Rol_Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CyanCMS.Domain.Entities.Company", b =>
                {
                    b.HasOne("CyanCMS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CyanCMS.Domain.Entities.User", b =>
                {
                    b.HasOne("CyanCMS.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("Rol_Id");

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
